#!/usr/bin/env ruby
# frozen_string_literal: true

if Dir['markdown-resume']
  puts 'markdown-resume repo has already been cloned.'
else
  puts 'Cloning markdown-resume repo...'
  `git clone https://github.com/there4/markdown-resume.git`
end

if `which php71`
  puts 'PHP is already installed.'
else
  puts 'Installing PHP...'
  `brew install php71 composer`
end

puts 'Ensuring Composer is up to date...'
`(cd markdown-resume; composer install)`

puts 'Building resume documents...'
`cp src/documents/resume.md markdown-resume/examples/source/resume-candidate.md`
`(cd markdown-resume; ./bin/md2resume html examples/source/resume-candidate.md examples/output/)`
`mv markdown-resume/examples/output/resume-candidate.html src/documents/resume.html`
`(cd markdown-resume; ./bin/md2resume pdf examples/source/resume-candidate.md examples/output/)`
`mv markdown-resume/examples/output/resume-candidate.pdf src/documents/resume.pdf`
