#!/usr/bin/env ruby
# frozen_string_literal: true

if `which resume`
  puts 'resume-cli is already installed. Skipping step...'
else
  puts 'Installing resume-cli...'
  `npm install -g resume-cli`
  `npm install -g jsonresume-theme-spartan`
  puts 'Completed installing resume-cli!'
end

puts 'Checking validity of resume.json...'

if `(cd src/documents; resume validate)`
  puts 'Valid!'
else
  puts 'Aborting early due to invalid schema...'
  return nil
end

puts 'Exporting to PDF...'
`(cd src/documents; resume export resume.pdf --format pdf --theme spartan)` && (puts 'PDF exported!')

puts 'Exporting to HTML...'
`(cd src/documents; resume export resume.html --format html --theme spartan)` && (puts 'HTML exported!')
